stages:
  - test
variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2
services:
    - name: zedsh/dind_ds
      alias: docker

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

run tests in docker:
  stage: test
  only: [zed_tests_now]
  when: always
  variables:
    GIT_SUBMODULE_STRATEGY: none

  before_script:
    - apk update
    - apk add --no-cache openrc
    - apk add --no-cache openssh
    - apk add --no-cache git
    - apk add --no-cache bash
    - apk add --no-cache docker
    - apk add py-pip --no-cache
    - pip install docker-compose
    - rc-update add sshd
    - mkdir ~/.ssh/
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - sed -i 's/# Host \*/Host \*/' /etc/ssh/ssh_config
    - sed -i 's/#   StrictHostKeyChecking ask/    StrictHostKeyChecking no/' /etc/ssh/ssh_config
    - git submodule sync
    - git submodule update --init
  script:
    - echo START TESTS
    - cd docker
    - pwd
    - ls -la
    - printenv
    - id
    - echo "$USER - user"
    - bash dctl.sh up silent
    - sleep 60
    - bash dctl.sh db renew
    - bash dctl.sh run composer install
    - bash dctl.sh test
