<?php
if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) {
    die();
}

\CBitrixComponent::includeComponentClass('system:standard.elements.list');

class RegFormComponent extends StandardElementListComponent
{
    public function getResult()
    {
        // TODO: customize autogenerated component template 
        $this->arResult = [
            'test value a',
            'test value b',
            'test value c',
        ];
    }
}
